### PR TITLE
Few little updates

### PR DESCRIPTION
**Pull request by ianharrigan**
Impressive work! Ive made a couple of changes (you will want to test them out though if / before you merge ofc)

* The caret index isnt always the one after the mouse position on click, it depends on where you click - this feels more natural as if you select to the far left of an "m" it the caret will be before the "m" not after
* The mouse cursor "I-Beam" is now calculated on the font size - this was because when made the font size 12 the cursor looked strange
* Now when you select the text, the colour of the selected text can change colour (making it much more obvious / natural) - this is an initial implementation and should certainly be refactored
* Ive made the internal scrollbar optional (defaults to true) - this is because not only did it not work, but also i would certainly like to use this library for HaxeUI (haxeui-kha) and thus would want my own scrollbars to provide that functionality

Again, very impressive work - there are a few little glitches, but in the main this component works absolutely great - highly looking forward to updates on this! Keep it up!

image

### CODE REVIEW

**Comment by tienery** [comment]
Many thanks for this. I will take a look at this on your branch and make any tweaks if necessary before I merge.

As you should know, if it were not for me initially paying @RobDangerous to help develop this project, functions in Kha such as `drawCharacters` would not exist. True enough, there are many changes here required, but it is coming along for sure!

**Comment by tienery** [comment]
As for the scrollbar, that was I believe on the TODO list. If not, then it's perhaps because I forgot to add it? >.< Nevertheless, I know it needs implementing. Will probably do it either today or tomorrow.

**Comment by ianharrigan** [comment]
Fair enough - would be nice if it was 100% optional, as i mentioned, the idea would be to use this in haxeui-kha and therefore i have my own scrollbar implementations. Also, are there plans to be able to use this as a single line, non-wrapped text input (ie, scrolling horizontally on a single line)

**Comment by tienery** [comment]
Yes, also a TODO. There needs to be refactoring in the scrolling functionality for this to happen, though. I will update the `TODO.txt` shortly.

**Comment by tienery** [comment]
I've merged most of the stuff you did, except the conversion to using a time task for key repeat. It has unwanted behaviour, such as when simply pressing a key once is interpreted as a repeated event. It feels more natural for there to be a delay between whether to repeat a key or not.

Secondly, I'm not a big fan of using callbacks in functions like that. It's okay to do it as part of native Kha, but I want to avoid excessive use of it. Callbacks slow things down, more often than not.

**Comment by ianharrigan** [comment]
Are you sure? The "Improve repeat key press handling" should fix the issues, its certainly a more correct way to do things - that kind of logic doesn't really make any sense to be in the render loop - also, your original repeat handling code had issues too of first key press being resulting in 3 keystrokes being added - its your call ofc - but as i mentioned, that kind of stuff in the render function is strange.

**Comment by tienery** [comment]
"its certainly a more correct way to do things" that's more subjective than objective.

Regardless, though. Now that I begin to think about it, perhaps it can be repeated every other frame. I'll have to re-implement it in my own code. At the time, it didn't make sense to place it in a separate time task, but for now it isn't a major issue.

**Pull request merged**
