### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by ianharrigan**
Few "little" up dates here if you are interested - mainly around scrollbars and fixing interactions with multiple textboxes. Im noticing some issues around horizontal scrolling and selections on strings with newlines in the them - but ill look another time a bit deeper. 

image

... and in case you are interested, this is my test app:

```
class Main {
	static var textBox1;
	static var textBox2;
	static var textBox3;
	static var textBox4;

    static var lorem = ("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, "
			+ "sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, "
			+ "sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. "
			+ "Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. "
			+ "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, "
			+ "sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, "
			+ "sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. "
			+ "Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. "
			+ "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, "
			+ "sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, "
			+ "sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. "
			+ "Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.");
    
    static var linebreaks = ("Line 1\nLine 2\nLine 3\nLine 4\nLine 5\nLine 5\nLine 6\nLine 7\nThis is a random long line without line breaks in it to test wordwrapping out\nLine 8\nLine 9\nLine 10\nLine 11\nLine 12\nLine 13\nLine 14\nLine 15");
            
	public static function main() {
		System.init({title: "TextBox", width: 1024, height: 768}, function () {
			Assets.loadEverything(function () {
				
                textBox1 = new TextBox(10, 10, 200, 200, Assets.fonts.LiberationSans_Regular, 14);
                textBox1.multiline = true;
                textBox1.wordWrap = true;
                textBox1.setText(lorem);
                
                textBox2 = new TextBox(220, 10, 200, 200, Assets.fonts.LiberationSans_Regular, 14);
                textBox2.useScrollBar = false;
                textBox2.multiline = true;
                textBox2.wordWrap = true;
                textBox2.setText(lorem);

                textBox3 = new TextBox(10, 220, 200, 200, Assets.fonts.LiberationSans_Regular, 14);
                textBox3.wordWrap = true;
                textBox3.setText(linebreaks);
                
                textBox4 = new TextBox(220, 220, 200, 200, Assets.fonts.LiberationSans_Regular, 14);
                textBox4.wordWrap = false;
                textBox4.setText(linebreaks);
                
				System.notifyOnRender(render);
				//Scheduler.addTimeTask(textBox1.update, 0, 1 / 60);
			});
		});
	}

	static function render(framebuffer: Framebuffer): Void {
		var g = framebuffer.g2;
		g.begin(true, Color.fromValue(0xFFFFFF));
		textBox1.render(g);
		textBox2.render(g);
		textBox3.render(g);
		textBox4.render(g);
		g.end();
	}
}
```

### CODE REVIEW

**Comment by tienery** [comment]
Yes, currently the horizontal scrolling has only really been covered in a single-line scenario, I have not tested it in a multiline scenario yet. I will definitely check this out, though, and see what I can do before implementing any further features. This could tick off one of the tasks, for sure.

Also, most of the `ScrollBar` class I like, but I'm not sure about making the scrollbar dependent on a TextBox. Surely it would make more logical sense if the ScrollBar has no dependency to the TextBox, and rather the other way around, especially if we want to have both a horizontal and vertical ScrollBar.

**Comment by ianharrigan** [comment]
Agreed, it was more of a refactor more than anything else - as i mentioned previously, im not that interested in the internal scrollbars - i dont really have a use for them, ill use HaxeUI scrollbars, but its not a HaxeUI lib, so wanted to keep at least the same functionality you have in the standalone lib.

**Comment by tienery** [comment]
I'm starting to look into it now and I'm having trouble trying to fix the issue around what you described earlier as "some issues around horizontal scrolling and selections on strings with newlines in the them".

In a single-line scenario, rendering appears perfectly fine and is as you would expect it to render. But in a multi-line scenario with word-wrapping off, the moment you scroll over the TextBox to highlight text toward the left or right, rendering of the caret and selection stops completely.

Even after returning to the start of the string to select any text there, the values in the debug information update fine, but the rendering of the caret and selection just isn't there. I'm trying to pin-point what the issue might be, but I'm having difficulty.

**Comment by tienery** [comment]
Nevermind, I found the problem. Will update shortly.

**Pull request merged**
